-- =============================================================================
-- Generated by lightline to lualine theme converter
--   https://gist.github.com/shadmansaleh/000871c9a608a012721c6acc6d7a19b9
-- License: MIT License
-- =============================================================================
local colors = {
  color0  = "#222433",
  color8  = "#929be5",
  color9  = "#4b4e6d",
  color10 = "#dc6f7a",
  color1  = "#73c1a9",
  color4  = "#282a3a",
  color5  = "#b871b8",
}

local dogrun = {
  insert = {
    a = { fg = colors.color0, bg = colors.color1, gui = "bold", },
    b = { fg = colors.color1, bg = colors.color4 },
  },
  visual = {
    a = { fg = colors.color0, bg = colors.color5, gui = "bold", },
    b = { fg = colors.color5, bg = colors.color4 },
  },
  normal = {
    a = { fg = colors.color0, bg = colors.color8, gui = "bold", },
    c = { fg = colors.color9, bg = colors.color4 },
    b = { fg = colors.color8, bg = colors.color4 },
  },
  replace = {
    a = { fg = colors.color0, bg = colors.color10, gui = "bold", },
    b = { fg = colors.color10, bg = colors.color4 },
  },
  inactive = {
    a = { fg = colors.color9, bg = colors.color4, gui = "bold", },
    c = { fg = colors.color9, bg = colors.color4 },
    b = { fg = colors.color9, bg = colors.color4 },
  },
}

return dogrun
