import = ["~/.config/alacritty/themes/themes/solarized_dark.toml"]

live_config_reload = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = false

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 1
option_as_alt = "OnlyLeft"
title = "Alacritty"

[window.padding]
x = 5
y = 5

