import = ["~/.config/alacritty/custom_themes/vague_theme.toml"]

live_config_reload = true

[cursor.style]
blinking = "Off"
shape = "Block"

[cursor.vi_mode_style]
blinking = "Off"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "BerkeleyMono Nerd Font"
# family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[window]
decorations = "buttonless"
dynamic_title = false
opacity = 1
option_as_alt = "OnlyLeft"
title = "Terminal"
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
