import = ["~/.config/alacritty/themes/themes/catppuccin.toml"]

live_config_reload = true

[cursor.style]
blinking = "Off"
shape = "Block"

[cursor.vi_mode_style]
blinking = "Off"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 1
option_as_alt = "OnlyLeft"
title = "Alacritty"

[window.padding]
x = 5
y = 5

