# vague

[colors.primary]
background = '#18191a'
foreground = '#cdcdcd'

[colors.cursor]
text = '#18191a'
cursor = '#be8c8c'

[colors.normal]
black = '#282830'   # color0
red = '#d2788c'     # color1
green = '#8faf77'   # color2
yellow = '#d2a374'  # color3
blue = '#7894ab'    # color4
magenta = '#8ca0dc' # color5
cyan = '#deb896'    # color6
white = '#cdcdcd'   # color7

[colors.bright]
black = '#646477'   # color8
red = '#be8c8c'     # color9
green = '#8faf77'   # color10
yellow = '#b4b4ce'  # color11
blue = '#7894ab'    # color12
magenta = '#8ca0dc' # color13
cyan = '#deb896'    # color14
white = '#cdcdcd'   # color15

[colors.dim]
black = '#282830'   # same as color0
red = '#a7657b'     # dimmed version of color1
green = '#7a9d68'   # dimmed version of color2
yellow = '#b39165'  # dimmed version of color3
blue = '#67829a'    # dimmed version of color4
magenta = '#7a8fc5' # dimmed version of color5
cyan = '#c3a581'    # dimmed version of color6
white = '#b3b3b3'   # dimmed version of color7
